In [1]:
import numpy as np


In [2]:
lst=[1,2,3,4]
lst.append(5)
lst

[1, 2, 3, 4, 5]

In [5]:
lst.remove(2)
lst

[1, 4, 5]

In [10]:
lstnp= np.array(lst)
lstnp
print(lstnp)

[1 4 5]


In [16]:
#matrix 
mtx1=np.ones((4,4))
matrix_nol=np.zeros((3,3))
mtxid= np.eye(6)
print(mtx1)
print(mtxid)
print(matrix_nol)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
rand=np.random.RandomState()
fake_log= rand.randint(1,5,size=5)
print(fake_log)

[4 3 3 1 3]


# excercise


In [109]:
mtx= np.zeros((4,4), dtype=int)
mtx[(0,1)]=1
mtx[(0,3)]=1
mtx[(1,0)]=1
mtx[(1,2)]=1
mtx[(2,1)]=1
mtx[(2,3)]=1
mtx[(3,0)]=1
mtx[(3,2)]=1
print(mtx)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [110]:
mtx= np.zeros((4,4), dtype=int)
mtx[::2,1::2]=1
mtx[1::2,::2]=1
print(mtx)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [77]:
#2
lst=list(range(0,30))
lstnp= np.array(lst)
mtx=lstnp.reshape(6,5)
#mtx[:,(1,0)]=mtx[:,(0,1)]
mtx[(1,0),:]=mtx[(0,1),:]
print(mtx)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [79]:
#Create a random vector with the number of elements as many as 20 and then sort them

rand=np.random.RandomState()
fake_log= rand.randint(1,20,size=20)
print(np.sort(fake_log))


[ 2  5  5  6  6  7  7  7  7  8  9  9  9 11 13 17 18 18 19 19]


    Create an array with random values
    With a lower limit value (-1);
    Superintendent (100) and;
    The order of the matrix is 5x5.
    Then, determine what are the min, max, mean, median, standard deviation values

In [89]:
rand=np.random.RandomState()
log= rand.randint(-1,100,size=25)
mtx=log.reshape(5,5)
print((mtx),'\nmin=',(np.min(mtx)),'\nmax=',(np.max(mtx)),'\nmean=',(np.mean(mtx)),'\nmedian=',(np.median(mtx)),
     '\nstandard deviation=',(np.std(mtx)))

[[91 59 74 85 13]
 [22 61 14 78 86]
 [65 68 66 50 78]
 [19  8  8 99 45]
 [ 9 42 75 74 16]] 
min= 8 
max= 99 
mean= 52.2 
median= 61.0 
standard deviation= 29.46048200556128


In [102]:

#Known Value x,y,v,w :
x = np.array([[1,2,4,6,8],[3,4,6,8,9]])
y = np.array([[5,6,8,9,10],[7,8,4,7,9]])
v = np.array([[9,10,2,2,2],[1,2,3,4,5],[1,1,1,1,1]])
w = np.array([[11,12,1,1,1],[2,2,2,1,8],[1,8,7,4,2]])

print(x,'\n',y,'\n',v,'\n',w)

[[1 2 4 6 8]
 [3 4 6 8 9]] 
 [[ 5  6  8  9 10]
 [ 7  8  4  7  9]] 
 [[ 9 10  2  2  2]
 [ 1  2  3  4  5]
 [ 1  1  1  1  1]] 
 [[11 12  1  1  1]
 [ 2  2  2  1  8]
 [ 1  8  7  4  2]]


In [105]:
x = x.view()
x

array([[1, 2, 4, 6, 8],
       [3, 4, 6, 8, 9]])

- x= matrix 2X5,dua dimensi
- y= matrix 2X5
- v= matrix 3X5
- w= matrix 3X5